### ISSUE TITLE
TODO - Road to Proof of Concept

### ISSUE THREAD

**Issue by retreat896** [retreat896/Html2ZPL#2]
# TODO
## Editor Features
- [ ] Add Labels to the editor
  - [ ] Implement label rendering
  - [ ] Handle label selection and focus
- [ ] Edit Label Properties
  - [ ] Edit Label Sizes
  - [ ] Edit Label Positions
  - [ ] Edit Label Options
- [ ] Show Label Preview
  - [ ] Implement preview rendering
  - [ ] Update preview on label changes
- [ ] Change when label is previewed
  - [ ] Implement preview toggle
  - [ ] Allow on save and on change.

## Item Management
- [ ] Dynamic item creation
- [ ] Multiple items
  - [ ] Implement item list rendering
  - [ ] Handle item selection and focus
- [ ] Add and remove items
  - [ ] Implement item addition
  - [ ] Implement item removal
  - [ ] Handle item deletion confirmation

## Import/Export
- [ ] Import zpl labels from file
  - [ ] Implement file upload handling
  - [ ] Parse zpl file format
- [ ] Export zpl labels to different types of files
  - [ ] Implement file export handling
  - [ ] Support multiple file formats (e.g. PDF, PNG, etc.)

## Item Options
- [ ] Item options
  - [ ] Implement option rendering
  - [ ] Handle option changes

## ZPL Elements
- [ ] ZPL images
  - [ ] Implement image rendering
  - [ ] Handle image uploads
- [ ] ZPL barcodes
  - [ ] Implement barcode rendering
  - [ ] Handle barcode data input
- [ ] ZPL text
  - [ ] Implement text rendering
  - [ ] Handle text input
- [ ] ZPL options
  - [ ] Implement option rendering
  - [ ] Handle option changes

## Saving and Loading
- [ ] Cloud saving and loading
  - [ ] Implement cloud storage integration
  - [ ] Handle cloud save and load operations
- [ ] Local save and load
  - [ ] Implement local storage handling
  - [ ] Handle local save and load operations
